//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoeMobile.Web.news {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtintro;
		protected global::System.Web.UI.WebControls.TextBox txtgen_time;
		protected global::System.Web.UI.WebControls.TextBox txtwriter;
		protected global::System.Web.UI.WebControls.TextBox txttitle;
		protected global::System.Web.UI.WebControls.TextBox txtcontent;
		protected global::System.Web.UI.WebControls.TextBox txtitemid;
		protected global::System.Web.UI.WebControls.TextBox txtpasscheked;
		protected global::System.Web.UI.WebControls.TextBox txtkeyword;
		protected global::System.Web.UI.WebControls.TextBox txtdefault_news;
		protected global::System.Web.UI.WebControls.TextBox txtclicked;
		protected global::System.Web.UI.WebControls.TextBox txtnews_url;
		protected global::System.Web.UI.WebControls.TextBox txtimage_url;
		protected global::System.Web.UI.WebControls.TextBox txtcomment_sum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
