//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoeMobile.Web.news {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblidnews;
	protected global::System.Web.UI.WebControls.Label lblintro;
	protected global::System.Web.UI.WebControls.Label lblgen_time;
	protected global::System.Web.UI.WebControls.Label lblwriter;
	protected global::System.Web.UI.WebControls.Label lbltitle;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lblitemid;
	protected global::System.Web.UI.WebControls.Label lblpasscheked;
	protected global::System.Web.UI.WebControls.Label lblkeyword;
	protected global::System.Web.UI.WebControls.Label lbldefault_news;
	protected global::System.Web.UI.WebControls.Label lblclicked;
	protected global::System.Web.UI.WebControls.Label lblnews_url;
	protected global::System.Web.UI.WebControls.Label lblimage_url;
	protected global::System.Web.UI.WebControls.Label lblcomment_sum;


       
    }
}
