//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoeMobile.Web.images {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblimage_id;
		protected global::System.Web.UI.WebControls.TextBox txtimage_src;
		protected global::System.Web.UI.WebControls.TextBox txtimage_owner;
		protected global::System.Web.UI.WebControls.TextBox txtdemo;
		protected global::System.Web.UI.WebControls.TextBox txtuid;
		protected global::System.Web.UI.WebControls.TextBox txttrace_id;
		protected global::System.Web.UI.WebControls.TextBox txtlocation_id;
		protected global::System.Web.UI.WebControls.TextBox txtbdata;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
